import Head from "next/head";
import {
  About,
  Blog,
  Clients,
  Contact,
  Footer,
  Hero,
  Navbar,
  Skills,
} from "../components";
export default function Home() {
  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Ghalitsar Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Blog />
      {/* <Skills /> */}
      <Clients />
      <Contact />
      <Footer />
    </div>
  );
}
